---
# tasks file for mariaDB

- name: Installing Mariadb Packages
  yum:
    name: "{{item}}"
    state: present
  with_items:
        - "{{mariadb_packages}}"


- name: start mariaDb Service
  systemd:
   name: mariadb
   state: started
   enabled: yes
  register: output

- debug:
    msg: "{{output}}"

- name: remove Anonymous user
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: Remove test database
  mysql_db:
    db: test
    host: localhost
    state: absent

